"""Dependency license inventory (spec section 16: component inventory).

Writes docs/LICENSES.md and exits non-zero if any dependency has a license
outside the permissive allow-list (no copyleft, no proprietary, no unknown).

    python scripts/license_inventory.py            # Python + Rust (needs cargo)
    python scripts/license_inventory.py --python   # Python only
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from importlib.metadata import PackageNotFoundError, distribution
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ALLOWED = {"MIT", "MIT-0", "Apache-2.0", "BSD-1-Clause", "BSD-2-Clause", "BSD-3-Clause", "ISC", "Zlib",
           "Unicode-3.0", "Unicode-DFS-2016", "Unlicense", "CC0-1.0", "PSF-2.0", "0BSD", "BSL-1.0",
           "Apache-2.0 WITH LLVM-exception"}
CLASSIFIERS = {"MIT License": "MIT", "Apache Software License": "Apache-2.0", "BSD License": "BSD-3-Clause",
               "Python Software Foundation License": "PSF-2.0", "ISC License (ISCL)": "ISC"}


def permitted(expr: str) -> bool:
    """Tiny SPDX evaluator: OR = any side allowed, AND = all sides allowed."""
    expr = expr.replace("/", " OR ").strip()
    if not expr:
        return False
    depth, parts = 0, []
    # split on top-level OR
    buf = ""
    for tok in re.split(r"(\(|\)|\s+OR\s+)", expr):
        if tok == "(":
            depth += 1
        elif tok == ")":
            depth -= 1
        if depth == 0 and tok and re.fullmatch(r"\s+OR\s+", tok):
            parts.append(buf)
            buf = ""
        else:
            buf += tok or ""
    parts.append(buf)
    if len(parts) > 1:
        return any(permitted(p) for p in parts)
    e = parts[0].strip()
    if e.startswith("(") and e.endswith(")"):
        return permitted(e[1:-1])
    if " AND " in e:
        return all(permitted(p) for p in e.split(" AND "))
    return e in ALLOWED


def python_deps() -> list[tuple[str, str, str, str]]:
    rows = []
    for req_file, scope in (("requirements.txt", "runtime"), ("requirements-dev.txt", "dev/test")):
        for line in (ROOT / req_file).read_text().splitlines():
            name = line.split("==")[0].strip()
            if not name or name.startswith("#"):
                continue
            try:
                m = distribution(name).metadata
            except PackageNotFoundError:
                rows.append((name, "?", "NOT INSTALLED", scope))
                continue
            lic = m.get("License-Expression") or ""
            if not lic:
                cls = [CLASSIFIERS.get(c.split("::")[-1].strip()) for c in (m.get_all("Classifier") or [])
                       if c.startswith("License")]
                lic = " OR ".join(c for c in cls if c) or (m.get("License") or "").strip()
            rows.append((name, m["Version"], lic, scope))
    return rows


def rust_deps() -> list[tuple[str, str, str, str]]:
    out = subprocess.run(["cargo", "metadata", "--format-version", "1", "--features", "localnet"],
                         cwd=ROOT / "contracts" / "escrow", capture_output=True, text=True, check=True)
    meta = json.loads(out.stdout)
    rows = []
    for p in sorted(meta["packages"], key=lambda p: p["name"]):
        if p["name"] == "cripito-escrow":
            continue
        rows.append((p["name"], p["version"], p.get("license") or "", "rust (program/localnet)"))
    return rows


def main() -> int:
    rows = python_deps()
    if "--python" not in sys.argv:
        rows += rust_deps()
    bad = [r for r in rows if not permitted(r[2])]
    lines = ["# Dependency licenses", "",
             "Generated by `python scripts/license_inventory.py`. Cripito itself is MIT (see `LICENSE`).",
             "Allowed: permissive licenses only (" + ", ".join(sorted(ALLOWED)) + ").", "",
             f"**{len(rows)} dependencies, {len(bad)} outside the allow-list.**", "",
             "| Package | Version | License | Scope |", "|---|---|---|---|"]
    lines += [f"| {n} | {v} | {lic} | {s} |" for n, v, lic, s in rows]
    if "--python" not in sys.argv:
        (ROOT / "docs" / "LICENSES.md").write_text("\n".join(lines) + "\n")
    for n, v, lic, s in bad:
        print(f"NOT ALLOWED: {n} {v} ({lic or 'no license metadata'}) [{s}]")
    print(f"{len(rows)} dependencies checked, {len(bad)} problems")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
